name: Dependency checker

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      id: maven
      run: mvn verify -P dependency-check

    - name: Upload Dependency Check Report
      id: upload-tests
      uses: actions/upload-artifact@v4.0.0
      with:
        name: dependency-check
        path: target/dependency-check-report.html
        retention-days: 1
